run:
  tests: true
  concurrency: 4
  timeout: 3m
  issue-exit-code: 0

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  unique-by-line: true

linters-settings:
  errorlint:
    errorf: true
    asserts: true
    comparison: true

  dupl:
    threshold: 100

  errcheck:
    ignore: fmt:.*,io/ioutil:^Read.*
    exclude-functions:
      - io.Copy(*bytes.Buffer)
      - io.Copy(os.Stdout)

  funlen:
    lines: 80
    statements: 40

  goconst:
    min-len: 3
    min-occurrences: 3
    ignore-tests: false
    numbers: true

  gocyclo:
    min-complexity: 20

  gosimple:
    go: "1.16"
    checks: ["all"]

  govet:
    check-shadowing: true
    fieldalignment: true

  staticcheck:
    go: "1.16"
    checks: ["all"]

  stylecheck:
    go: "1.16"
    # https://staticcheck.io/docs/options#checks
    checks: [ "all", "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022" ]
    # https://staticcheck.io/docs/options#dot_import_whitelist
    dot-import-whitelist:
      - fmt
    # https://staticcheck.io/docs/options#initialisms
    initialisms: [ "ACL", "API", "ASCII", "CPU", "CSS", "DNS", "EOF", "GUID", "HTML", "HTTP", "HTTPS", "ID", "IP", "JSON", "QPS", "RAM", "RPC", "SLA", "SMTP", "SQL", "SSH", "TCP", "TLS", "TTL", "UDP", "UI", "GID", "UID", "UUID", "URI", "URL", "UTF8", "VM", "XML", "XMPP", "XSRF", "XSS" ]
    # https://staticcheck.io/docs/options#http_status_code_whitelist
    http-status-code-whitelist: [ "200", "400", "404", "500" ]

  unused:
    go: "1.16"
    check-exported: false

  whitespace:
    multi-if: true
    multi-func: true

linters:
  enable-all: false
  disable-all: true
  enable:
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - bodyclose
    - exportloopref
    - gocritic
    - goprintffuncname
    - gosec
    - prealloc
    - stylecheck
    - unconvert
    - whitespace
    - errorlint

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - goconst
        - errcheck
        - dupl
        - gosec
        - govet
        - funlen
        - gocognit



