// struct-summary demonstrates consumer-owned generation from Gentools metadata.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strconv"
	"strings"

	"github.com/kucjac/gentools/parser"
	"github.com/kucjac/gentools/types"
)

func main() {
	input := flag.String("input", "", "directory containing Go source")
	output := flag.String("output", "", "generated Go output path")
	flag.Parse()
	if *input == "" || *output == "" {
		fmt.Fprintln(os.Stderr, "-input and -output are required")
		os.Exit(2)
	}
	if err := generate(*input, *output); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func generate(input, output string) error {
	pkgs, err := parser.LoadPackages(parser.LoadConfig{Paths: []string{input}})
	if err != nil {
		return err
	}
	var names []string
	for _, pkg := range pkgs {
		for name, value := range pkg.Types {
			if _, ok := value.(*types.Struct); ok {
				names = append(names, name)
			}
		}
	}
	sort.Strings(names)
	var b bytes.Buffer
	b.WriteString("// Code generated by gentools struct-summary; DO NOT EDIT.\n\npackage generated\n\n")
	quoted := make([]string, len(names))
	for i, name := range names {
		quoted[i] = strconv.Quote(name)
	}
	fmt.Fprintf(&b, "var StructNames = []string{%s}\n", strings.Join(quoted, ", "))
	formatted, err := format.Source(b.Bytes())
	if err != nil {
		return err
	}
	return os.WriteFile(output, formatted, 0o644)
}
