package main

import (
	"os"
	"path/filepath"
	"testing"
)

func TestGenerate(t *testing.T) {
	out := filepath.Join(t.TempDir(), "summary.go")
	if err := generate("testdata", out); err != nil {
		t.Fatal(err)
	}
	b, err := os.ReadFile(out)
	if err != nil {
		t.Fatal(err)
	}
	if string(b) != "// Code generated by gentools struct-summary; DO NOT EDIT.\n\npackage generated\n\nvar StructNames = []string{\"Account\", \"Session\"}\n" {
		t.Fatalf("unexpected output: %s", b)
	}
}

func TestGenerateRejectsMissingInput(t *testing.T) {
	if err := generate("missing", filepath.Join(t.TempDir(), "summary.go")); err == nil {
		t.Fatal("expected error")
	}
}
