// struct-accessors generates getters for selected fields of one Go struct.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"go/token"
	"os"
	"strings"

	"github.com/kucjac/gentools/parser"
	gentypes "github.com/kucjac/gentools/types"
)

func main() {
	input := flag.String("input", "", "directory containing Go source")
	typeName := flag.String("type", "", "struct name to inspect")
	fields := flag.String("fields", "", "comma-separated exported fields to generate")
	output := flag.String("output", "", "generated Go output path")
	flag.Parse()
	if *input == "" || *typeName == "" || *fields == "" || *output == "" {
		fmt.Fprintln(os.Stderr, "-input, -type, -fields, and -output are required")
		os.Exit(2)
	}
	if err := generate(*input, *typeName, strings.Split(*fields, ","), *output); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func generate(input, typeName string, fieldNames []string, output string) error {
	pkgs, err := parser.LoadPackages(parser.LoadConfig{Paths: []string{input}})
	if err != nil {
		return err
	}
	target, err := findStruct(pkgs, typeName)
	if err != nil {
		return err
	}
	fields, err := selectFields(target, fieldNames)
	if err != nil {
		return err
	}

	var source bytes.Buffer
	fmt.Fprintf(&source, "// Code generated by gentools struct-accessors; DO NOT EDIT.\n\npackage %s\n", target.Pkg.Identifier)
	for _, field := range fields {
		fmt.Fprintf(&source, "\nfunc (v %s) Get%s() %s {\n\treturn v.%s\n}\n", target.TypeName, field.Name, field.Type.Name(true, target.Pkg.Path), field.Name)
	}
	formatted, err := format.Source(source.Bytes())
	if err != nil {
		return fmt.Errorf("format generated accessors: %w", err)
	}
	return os.WriteFile(output, formatted, 0o644)
}

func findStruct(pkgs gentypes.PackageMap, name string) (*gentypes.Struct, error) {
	for _, pkg := range pkgs {
		value, ok := pkg.GetType(name)
		if !ok {
			continue
		}
		if target, ok := value.(*gentypes.Struct); ok {
			return target, nil
		}
	}
	return nil, fmt.Errorf("struct %q was not found", name)
}

func selectFields(target *gentypes.Struct, names []string) ([]gentypes.StructField, error) {
	available := make(map[string]gentypes.StructField, len(target.Fields))
	for _, field := range target.Fields {
		available[field.Name] = field
	}
	selected := make([]gentypes.StructField, 0, len(names))
	seen := make(map[string]bool, len(names))
	for _, name := range names {
		name = strings.TrimSpace(name)
		if name == "" {
			return nil, fmt.Errorf("field names must not be empty")
		}
		field, ok := available[name]
		if !ok {
			return nil, fmt.Errorf("struct %s has no field %q", target.TypeName, name)
		}
		if !token.IsExported(field.Name) {
			return nil, fmt.Errorf("field %s.%s is not exported", target.TypeName, field.Name)
		}
		if seen[name] {
			return nil, fmt.Errorf("field %s was requested more than once", name)
		}
		seen[name] = true
		selected = append(selected, field)
	}
	return selected, nil
}
