// Command testinventory validates Gentools' behavior inventory.
package main

import (
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"go/ast"
	"os"
	"sort"
	"strings"

	"golang.org/x/tools/go/packages"
)

type entry struct {
	ID        string `json:"id"`
	Symbol    string `json:"symbol"`
	Owner     string `json:"owner"`
	Risk      string `json:"risk"`
	TestLevel string `json:"test_level"`
	Status    string `json:"status"`
	Evidence  string `json:"evidence"`
	Rationale string `json:"rationale"`
	Priority  string `json:"priority"`
}
type inventory struct {
	Entries []entry `json:"entries"`
}

func main() {
	if len(os.Args) < 2 || os.Args[1] != "assess" {
		fmt.Fprintln(os.Stderr, "usage: testinventory assess --inventory FILE --report FILE [--coverage FILE]")
		os.Exit(2)
	}
	fs := flag.NewFlagSet("assess", flag.ExitOnError)
	invPath := fs.String("inventory", "docs/testing/behavior-inventory.json", "inventory JSON")
	report := fs.String("report", "docs/testing/behavior-inventory.md", "report Markdown")
	fs.String("coverage", "", "coverage profile retained as supporting evidence")
	fs.Parse(os.Args[2:])
	if err := assess(*invPath, *report); err != nil {
		fmt.Fprintln(os.Stderr, "testinventory:", err)
		os.Exit(1)
	}
}

func assess(invPath, report string) error {
	data, err := os.ReadFile(invPath)
	if err != nil {
		return err
	}
	var inv inventory
	if err := json.Unmarshal(data, &inv); err != nil {
		return err
	}
	if len(inv.Entries) == 0 {
		return errors.New("inventory is empty")
	}
	seen, covered := map[string]bool{}, map[string]bool{}
	for _, e := range inv.Entries {
		if e.ID == "" || e.Symbol == "" || e.Owner == "" || e.Risk == "" || e.Status == "" || e.Evidence == "" {
			return fmt.Errorf("incomplete inventory entry %q", e.ID)
		}
		if seen[e.ID] {
			return fmt.Errorf("duplicate inventory id %q", e.ID)
		}
		seen[e.ID] = true
		if _, err := os.Stat(e.Evidence); err != nil {
			return fmt.Errorf("%s evidence %q: %w", e.ID, e.Evidence, err)
		}
		if e.Status == "gap" && e.Priority == "" {
			return fmt.Errorf("gap %s has no priority", e.ID)
		}
		if e.Status == "excluded" && e.Rationale == "" {
			return fmt.Errorf("excluded entry %s has no rationale", e.ID)
		}
		if e.Risk == "high" && e.Status == "gap" {
			return fmt.Errorf("high-risk gap %s is not approved", e.ID)
		}
		covered[e.Symbol] = true
	}
	exports, err := exportedSymbols()
	if err != nil {
		return err
	}
	for _, symbol := range exports {
		if !covered[symbol] && !covered[packageWildcard(symbol)] {
			return fmt.Errorf("unclassified exported symbol %s", symbol)
		}
	}
	entries := append([]entry(nil), inv.Entries...)
	sort.Slice(entries, func(i, j int) bool { return entries[i].ID < entries[j].ID })
	var b strings.Builder
	b.WriteString("# Behavior Inventory Report\n\nGenerated by `testinventory assess`; coverage is supporting evidence, not proof of behavioral completeness.\n\n`parser.*` and `types.*` are intentional, reviewed package-level public API groups. They keep the inventory maintainable while the linked evidence and high-risk internal entry retain behavior-level scrutiny.\n\n| ID | Symbol | Risk | Test level | Status | Evidence |\n|---|---|---|---|---|---|\n")
	for _, e := range entries {
		fmt.Fprintf(&b, "| %s | %s | %s | %s | %s | `%s` |\n", e.ID, e.Symbol, e.Risk, e.TestLevel, e.Status, e.Evidence)
	}
	return os.WriteFile(report, []byte(b.String()), 0o644)
}

func packageWildcard(symbol string) string { return strings.Split(symbol, ".")[0] + ".*" }

func exportedSymbols() ([]string, error) {
	var result []string
	for _, dir := range []string{"parser", "types"} {
		pkgs, err := packages.Load(&packages.Config{Mode: packages.NeedName | packages.NeedSyntax}, "./"+dir)
		if err != nil {
			return nil, err
		}
		for _, pkg := range pkgs {
			if len(pkg.Errors) > 0 {
				return nil, fmt.Errorf("load %s: %w", dir, pkg.Errors[0])
			}
			for _, file := range pkg.Syntax {
				for _, decl := range file.Decls {
					switch d := decl.(type) {
					case *ast.FuncDecl:
						if d.Recv == nil && d.Name.IsExported() {
							result = append(result, pkg.Name+"."+d.Name.Name)
						}
					case *ast.GenDecl:
						for _, spec := range d.Specs {
							switch s := spec.(type) {
							case *ast.TypeSpec:
								if s.Name.IsExported() {
									result = append(result, pkg.Name+"."+s.Name.Name)
								}
							case *ast.ValueSpec:
								for _, n := range s.Names {
									if n.IsExported() {
										result = append(result, pkg.Name+"."+n.Name)
									}
								}
							}
						}
					}
				}
			}
		}
	}
	sort.Strings(result)
	return result, nil
}
