name: Build, Test and Lint

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  GOPRIVATE: "github.com/kucjac"

jobs:
  build-and-test:
    name: Build and Test - Go ${{ matrix.go }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      CGO_ENABLED: 0
    strategy:
      matrix:
        go: ['1.17', '1.16', '1.15']
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - name: Checkout and prepare environment
        uses: actions/checkout@v2

      - name: Setup Golang with cache
        uses: magnetikonline/action-golang-cache@v1
        with:
          go-version: ~${{ matrix.go }}

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Run 'go vet'
        run: |
          go vet ./...

      - name: Test
        run: |
          go test -count=1 ./...

  golangci-lint:
    name: GolangCI-Lint - Go ${{ matrix.go }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs:
      - build-and-test
    strategy:
      matrix:
        go: ['1.17', '1.16', '1.15']
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - name: Checkout code into the Go module directory
        uses: actions/checkout@v2

      - name: Use cache
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod

      - name: Check linters
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.42.1
